# What the leaf solve stopped at roundoff moves on phylloptim's golden grid
# (prereg.txt, eighth extension): golden files generated by the base's and the
# branch's own test programs, compared value by value, and the collar's
# operating points grouped by their kind before and after.
#   python3 leaf_golden.py BASE_GOLDEN_DIR NEW_GOLDEN_DIR
# Each directory is written, from a scratch directory holding golden/, by
#   tests/cpp/test_golden --generate; tests/cpp/test_golden --generate-optima;
#   tests/cpp/test_primitives --generate
# built from phylloptim 378b083 (BASE) and PHYLLOPTIM-17 (NEW).
import sys, csv, math, collections
def load(p):
    rows = list(csv.reader(open(p), delimiter='\t')); return rows[0], rows[1:]
def num(x):
    try: return float(x)
    except: return None
a, b = sys.argv[1], sys.argv[2]
for name in ['operating_points.tsv', 'psi_stem_optima.tsv', 'primitives.tsv']:
    ha, ra = load(f'{a}/{name}'); hb, rb = load(f'{b}/{name}')
    assert ha == hb and len(ra) == len(rb), name
    worst = {}; changed = 0; total = 0
    for x, y in zip(ra, rb):
        for h, u, v in zip(ha, x, y):
            fu, fv = num(u), num(v)
            if fu is None or fv is None: continue
            total += 1
            if (math.isnan(fu) and math.isnan(fv)) or fu == fv: continue
            changed += 1
            rel = abs(fu - fv) / max(abs(fu), abs(fv), 1e-300)
            worst[h] = max(worst.get(h, 0.0), rel)
    print(f'{name}: {changed} of {total} values differ')
    for h, r in sorted(worst.items(), key=lambda kv: -kv[1])[:6]:
        print(f'    {h:22s} worst relative {r:.3g}')
h, ra = load(f'{a}/psi_stem_optima.tsv'); _, rb = load(f'{b}/psi_stem_optima.tsv')
ki = h.index('kind')
g = collections.defaultdict(lambda: [0, 0, 0.0, 0])
for x, y in zip(ra, rb):
    worst = 0.0
    for col, u, v in zip(h, x, y):
        fu, fv = num(u), num(v)
        if fu is None or fv is None or (math.isnan(fu) and math.isnan(fv)) or fu == fv: continue
        worst = max(worst, abs(fu - fv) / max(abs(fu), abs(fv), 1e-300))
    e = g[(x[1], x[ki], y[ki])]; e[0] += 1; e[1] += worst > 1e-6; e[2] = max(e[2], worst); e[3] += worst > 1e-2
print('psi_stem_optima.tsv by solver and kind (before -> after): rows, rows moved over 1e-6, over 1e-2, worst relative')
for k in sorted(g):
    e = g[k]
    print(f'    {k[0]:11s} {k[1]:15s} -> {k[2]:15s} {e[0]:5d} {e[1]:5d} {e[3]:4d}  {e[2]:.3g}')
